pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    dotnet build -c $(buildConfiguration)

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    configuration: '$(buildConfiguration)'
    packagesToPack: '**/Tachocline/*.csproj'
    packDirectory: '$(build.artifactStagingDirectory)'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '0'
    minorVersion: '0'
    patchVersion: '2'

- task: DotNetCoreCLI@2
  inputs: 
    command: 'push'
    nuGetFeedType: 'external'
    packagesToPush: '$(build.artifactStagingDirectory)/*.nupkg'
    publishFeedCredentials: 'Tachocline Azure Pipeline'
